version: '3'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'databaseCarhunter'
      MYSQL_USER: 'usernameCarhunter'
      MYSQL_PASSWORD: 'passwordCarhunter'
      MYSQL_ROOT_PASSWORD: 'passwordRootCarhunter'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - carhunter:/var/lib/mysql

volumes:
  carhunter: